--- Day-04 — HR Analytics

-- Basic SQL Practice

-- 1. Display every column from the `HR_Attrition_Indian_Dataset.csv` table.
-- 2. Display only `EmployeeID`, `FullName`, `Department`, and `Designation`.
-- 3. Display the distinct values in the `Department` column.
-- 4. Find employees in the `IT` department.
-- 5. Find employees whose `Gender` is `Female`.
-- 6. Find employees older than 40.
-- 7. Find employees whose `MonthlySalary` is greater than 100000.
-- 8. Find employees whose `YearsWithCompany` is less than or equal to 2.
-- 9. Find employees whose `AppraisalRating` is not equal to 3.
-- 10. Find employees whose `JobSatisfaction` is between 3 and 4.
-- 11. Find employees whose `City` is either `Mumbai` or `Kolkata`.
-- 12. Find employees who are in the `HR` department and have `DoesOvertime` equal to `Yes`.
-- 13. Find employees whose `FullName` starts with the letter `A`.
-- 14. Find employees whose `Designation` contains the text `Officer`.
-- 15. Find employees whose `PreviousCompanies` is equal to 0.
-- 16. Find employees whose `DistanceFromHome` is greater than 20 and whose `LeavesTaken` is less than 15.
-- 17. Find employees whose `MaritalStatus` is not `Single`.
-- 18. Find employees who have not left the company by filtering `LeftCompany` = `No`.
-- 19. List employees ordered by `MonthlySalary` from highest to lowest.
-- 20. Display the first 10 employees ordered by `YearsWithCompany` from lowest to highest.
