--  Day-03 — Olist E-Commerce
--  Basic SQL Practice

-- 1. Display every column from the `olist_customers_dataset.csv` table.
-- 2. Display only `customer_id`, `customer_city`, and `customer_state` from `olist_customers_dataset.csv`.
-- 3. Display the distinct values in the `customer_state` column.
-- 4. Find customers whose `customer_state` is `SP`.
-- 5. Find customers whose `customer_city` is `franca`.
-- 6. Find customers whose `customer_zip_code_prefix` is greater than 50000.
-- 7. Find customers whose `customer_zip_code_prefix` is less than or equal to 10000.
-- 8. Find customers whose `customer_city` is not `sao paulo`.
-- 9. Find customers whose `customer_city` starts with the letter `s`.
-- 10. Find customers whose `customer_state` is either `SP` or `RJ`.
-- 11. Display every column from the `olist_orders_dataset.csv` table.
-- 12. Find orders whose `order_status` is `delivered`.
-- 13. Find orders whose `order_status` is not `canceled`.
-- 14. Find orders purchased between `2017-01-01` and `2017-12-31`.
-- 15. Find orders where `order_delivered_customer_date` is `NULL`.
-- 16. Find orders where `order_delivered_customer_date` is not `NULL`.
-- 17. Display every column from the `olist_order_payments_dataset.csv` table where `payment_type` is `credit_card`.
-- 18. Find payment records where `payment_installments` is greater than 5.
-- 19. Display every column from the `olist_order_reviews_dataset.csv` table where `review_score` is less than or equal to 2.
-- 20. Display the first 10 rows from `olist_products_dataset.csv` ordered by `product_photos_qty` from highest to lowest.
